import type { Cluster, JiraOutputConfig } from "./types";

interface JiraIssueResponse {
  id: string;
  key: string;
  self: string;
}

/**
 * Create a Jira issue from a Signal intent gap cluster.
 * Uses the Jira REST API v3 (Cloud).
 */
export async function createJiraIssue(
  config: JiraOutputConfig,
  cluster: Cluster
): Promise<JiraIssueResponse> {
  const severityLabel =
    cluster.severity >= 70 ? "HIGH" : cluster.severity >= 40 ? "MEDIUM" : "LOW";

  const description = {
    version: 1,
    type: "doc",
    content: [
      {
        type: "heading",
        attrs: { level: 3 },
        content: [{ type: "text", text: "Business Case" }],
      },
      {
        type: "paragraph",
        content: [{ type: "text", text: cluster.business_case }],
      },
      {
        type: "heading",
        attrs: { level: 3 },
        content: [{ type: "text", text: "Recommended Action" }],
      },
      {
        type: "paragraph",
        content: [{ type: "text", text: cluster.recommended_action }],
      },
      {
        type: "heading",
        attrs: { level: 3 },
        content: [{ type: "text", text: "Evidence" }],
      },
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: `${cluster.evidence_count} signals · ${Math.round(cluster.confidence * 100)}% confidence · Severity ${cluster.severity}/100 (${severityLabel})`,
          },
        ],
      },
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: `Sources — Slack: ${cluster.source_breakdown.slack} · Email: ${cluster.source_breakdown.email} · WhatsApp: ${cluster.source_breakdown.whatsapp}`,
          },
        ],
      },
      ...(cluster.customer_quote
        ? [
            {
              type: "heading",
              attrs: { level: 3 },
              content: [{ type: "text", text: "Customer Voice" }],
            },
            {
              type: "blockquote",
              content: [
                {
                  type: "paragraph",
                  content: [
                    { type: "text", text: `"${cluster.customer_quote}"` },
                  ],
                },
              ],
            },
          ]
        : []),
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: "Generated by Signal · ",
            marks: [{ type: "em" }],
          },
          {
            type: "text",
            text: `View full brief →`,
            marks: [
              { type: "em" },
              {
                type: "link",
                attrs: {
                  href: `${process.env.NEXTAUTH_URL}/dashboard?gap=${cluster.id}`,
                },
              },
            ],
          },
        ],
      },
    ],
  };

  const body = {
    fields: {
      project: { key: config.project_key },
      summary: `[Signal] ${severityLabel}: ${cluster.title}`,
      description,
      issuetype: { name: "Story" },
      labels: ["signal", "product-gap"],
    },
  };

  const credentials = Buffer.from(`${config.email}:${config.api_token}`).toString("base64");

  const res = await fetch(`https://${config.domain}/rest/api/3/issue`, {
    method: "POST",
    headers: {
      Authorization: `Basic ${credentials}`,
      "Accept": "application/json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Jira API error ${res.status}: ${text}`);
  }

  return res.json() as Promise<JiraIssueResponse>;
}
